applications:
  argowf:                 false
  argo-events:            false
  cache:                  false
  ceph:                   false
  cert-manager:           true
  example-guestbook:      false
  grafana:                true
  harbor:                 false
  influxdb:               false
  ingress:                true
  jaeger-operator:        false
  kafka:                  false
  loadbalancer:           false
  loki:                   true
  nifi:                   false
  prometheus:             true
  rook:                   false
  thanos:                 false
  vault:                  false
  eo-kafka:              true
  eo-postgresql:         true
  eo-frontend:           true
  eo-auth:               true
  eo-emissions:          false
  eo-measurements:       false
  eo-meteringpoints:     false
  eo-technologies:       false
  eo-datahub2:           false
