# By setting the storage class, you enable the hard-coded ceph storageclass in the values files. If not set,
# the charts will default to the standard storage class
# storageClass: ceph-filesystem

# If registry is not set, it will pull from the default registries
# registry: <your-registry-here>

applications: 
  argowf:                 false
  argo-events:            false
  cache:                  false
  ceph:                   false
  cert-manager:           true
  example-guestbook:      false
  grafana:                true
  harbor:                 false
  influxdb:               false
  ingress:                true
  jaeger:                 false
  kafka:                  false
  loadbalancer:           false
  loki:                   true
  nifi:                   false
  ntp:                    false
  prometheus:             true
  rook:                   false
  thanos:                 false
  vault:                  false
  eo-kafka:              true
  eo-postgresql:         true
  eo-frontend:           true
  eo-auth:               true
  eo-emissions:          false
  eo-measurements:       false
  eo-meteringpoints:     false
  eo-technologies:       false
  eo-datahub2:           false
