name: ett
namespace: ett
description: Energy Track and Trace


project:
  name: ett
  server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  destinations: 
    - namespace: kube-system
      server: https://kubernetes.default.svc
apps:
  - name: ett-frontend
    source:
      repoURL: "https://github.com/Energinet-DataHub/greenforce-frontend.git"
      targetRevision: main
      path: chart
      valuesFile: "ett-frontend.yaml"
  - name: ett-auth
    source:
      repoURL: "https://github.com/Energy-Track-and-Trace/ett-auth.git"
      targetRevision: main
      path: chart
      valuesFile: "ett-auth-service.yaml"
  - name: ett-emissions
    source:
      repoURL: "https://github.com/Energy-Track-and-Trace/ett-emissions.git"
      targetRevision: main
      path: chart
      valuesFile: "ett-emissions.yaml"
  - name: ett-measurements
    source:
      repoURL: "https://github.com/Energy-Track-and-Trace/ett-measurements.git"
      targetRevision: main
      path: chart
      valuesFile: "ett-measurements.yaml"
  - name: ett-meteringpoints
    source:
      repoURL: "https://github.com/Energy-Track-and-Trace/ett-meteringpoints.git"
      targetRevision: main
      path: chart
      valuesFile: "ett-meteringpoints.yaml"
  - name: ett-technologies
    source:
      repoURL: "https://github.com/Energy-Track-and-Trace/ett-technologies.git"
      targetRevision: main
      path: chart
      valuesFile: "ett-technologies.yaml"
  - name: ett-datahub2
    source:
      repoURL: "https://github.com/Energy-Track-and-Trace/ett-datahub2.git"
      targetRevision: main
      path: chart
      valuesFile: "ett-datahub2.yaml"
